/*****************************************************************************
 * arch/renesas/include/rx66t/irq.h
 *
 *   Copyright (C) 2008-2019 Gregory Nutt. All rights reserved.
 *   Author: Gregory Nutt <gnutt@nuttx.org>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name NuttX nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

#ifndef __ARCH_RENESAS_INCLUDE_RX66T_IRQ_H
#define __ARCH_RENESAS_INCLUDE_RX66T_IRQ_H

/* SCI */

#define RX_RXI_IRQ_OFFSET       (0)                     /* RxIn */
#define RX_TXI_IRQ_OFFSET       (1)                     /* TxIn */
#define RX_ERI_IRQ_OFFSET       (2)                     /* ERIn */
#define RX_TEI_IRQ_OFFSET       (3)                     /* TEIn */
#define RX_SCI_NIRQS            (4)

# define RX66T_TRAP_IRQBASE   (0)
# define RX66T_TRAP0_IRQ      (RX66T_TRAP_IRQBASE)
# define RX66T_TRAP1_IRQ      (RX66T_TRAP_IRQBASE+1)
# define RX66T_TRAP2_IRQ      (RX66T_TRAP_IRQBASE+2)
# define RX66T_TRAP3_IRQ      (RX66T_TRAP_IRQBASE+3)
# define RX66T_TRAP4_IRQ      (RX66T_TRAP_IRQBASE+4)
# define RX66T_TRAP5_IRQ      (RX66T_TRAP_IRQBASE+5)
# define RX66T_TRAP6_IRQ      (RX66T_TRAP_IRQBASE+6)
# define RX66T_TRAP7_IRQ      (RX66T_TRAP_IRQBASE+7)
# define RX66T_TRAP8_IRQ      (RX66T_TRAP_IRQBASE+8)
# define RX66T_TRAP9_IRQ      (RX66T_TRAP_IRQBASE+9)
# define RX66T_TRAP10_IRQ     (RX66T_TRAP_IRQBASE+10)
# define RX66T_TRAP11_IRQ     (RX66T_TRAP_IRQBASE+11)
# define RX66T_TRAP12_IRQ     (RX66T_TRAP_IRQBASE+12)
# define RX66T_TRAP13_IRQ     (RX66T_TRAP_IRQBASE+13)
# define RX66T_TRAP14_IRQ     (RX66T_TRAP_IRQBASE+14)
# define RX66T_TRAP15_IRQ     (RX66T_TRAP_IRQBASE+15)
# define RX66T_BUSERR_IRQBASE (RX66T_TRAP_IRQBASE+16)

#if     defined(CONFIG_BSC) || defined(CONFIG_RX66T_BSC)
# define RX66T_BUSERR_IRQ     (RX66T_BUSERR_IRQBASE)
# define RX66T_RAMERR_IRQBASE (RX66T_BUSERR_IRQBASE+1)
#else
# define RX66T_RAMERR_IRQBASE (RX66T_BUSERR_IRQBASE)
#endif

#if     defined(CONFIG_RAM) || defined(CONFIG_RX66T_RAM)
# define RX66T_RAMERR_IRQ     (RX66T_RAMERR_IRQBASE)
# define RX66T_FIFERR_IRQBASE (RX66T_RAMERR_IRQBASE+1)
#else
# define RX66T_FIFERR_IRQBASE (RX66T_RAMERR_IRQBASE)
#endif

#if     defined(CONFIG_FIFERR) || defined(CONFIG_RX66T_FIFERR)
# define RX66T_FIFERR_IRQ     (RX66T_FIFERR_IRQBASE)
# define RX66T_FRDYI_IRQBASE  (RX66T_FIFERR_IRQBASE+1)
#else
# define RX66T_FRDYI_IRQBASE  (RX66T_FIFERR_IRQBASE)
#endif

#if     defined(CONFIG_FRDYI) || defined(CONFIG_RX66T_FRDYI)
# define RX66T_FRDYI_IRQ                (RX66T_FRDYI_IRQBASE)
# define RX66T_SWINT2_IRQBASE   (RX66T_FRDYI_IRQBASE+1)
#else
# define RX66T_SWINT2_IRQBASE   (RX66T_FRDYI_IRQBASE)
#endif

# define RX66T_SWINT2_IRQ               (RX66T_SWINT2_IRQBASE)
# define RX66T_SWINT_IRQBASE    (RX66T_SWINT2_IRQBASE+1)

# define RX66T_SWINT_IRQ                (RX66T_SWINT_IRQBASE)
# define RX66T_CMT0_IRQBASE         (RX66T_SWINT_IRQBASE+1)

#define RX66T_CMI0_IRQ              (RX66T_CMT0_IRQBASE)
#define RX66T_CMT1_IRQBASE      (RX66T_CMT0_IRQBASE + 1)

#ifdef CONFIG_RX66T_CMT1
#  define RX66T_CMI1_IRQ        (RX66T_CMT1_IRQBASE)
#  define RX66T_CMTW0_IRQBASE   (RX66T_CMT1_IRQBASE + 1)
#else
#  define RX66T_CMTW0_IRQBASE   (RX66T_CMT1_IRQBASE)
#endif

#ifdef CONFIG_RX66T_CMTW0
#  define RX66T_CMWI0_IRQ      (RX66T_CMTW0_IRQBASE)
#  define RX66T_CMTW1_IRQBASE  (RX66T_CMTW0_IRQBASE + 1)
#else
#  define RX66T_CMTW1_IRQBASE  (RX66T_CMTW0_IRQBASE)
#endif

#ifdef CONFIG_RX66T_CMTW1
#  define RX66T_CMWI1_IRQ      (RX66T_CMTW1_IRQBASE)
#  define RX66T_USB0_IRQBASE   (RX66T_CMTW1_IRQBASE + 1)
#else
#  define RX66T_USB0_IRQBASE   (RX66T_CMTW1_IRQBASE)
#endif

#ifdef CONFIG_RX66T_USB0
#  define RX66T_D0FIFO0_IRQ    (RX66T_USB0_IRQBASE)
#  define RX66T_D1FIFO0_IRQ    (RX66T_USB0_IRQBASE + 1)
#  define RX66T_RSPI0_IRQBASE  (RX66T_USB0_IRQBASE + 2)
#else
#  define RX66T_RSPI0_IRQBASE  (RX66T_USB0_IRQBASE)
#endif
#ifdef CONFIG_RX66T_RSPI0
#  define RX66T_SPRI0_IRQ      (RX66T_RSPI0_IRQBASE)
#  define RX66T_SPTI0_IRQ      (RX66T_RSPI0_IRQBASE + 1)
#  define RX66T_RSPI1_IRQBASE  (RX66T_RSPI0_IRQBASE + 2)
#else
#  define RX66T_RSPI1_IRQBASE  (RX66T_RSPI0_IRQBASE)
#endif

#ifdef CONFIG_RX66T_RSPI1
#  define RX66T_SPRI1_IRQ       (RX66T_RSPI1_IRQBASE)
#  define RX66T_SPTI1_IRQ       (RX66T_RSPI1_IRQBASE + 1)
#  define RX66T_QSPI_IRQBASE    (RX66T_RSPI1_IRQBASE + 2)
#else
#  define RX66T_QSPI_IRQBASE    (RX66T_RSPI1_IRQBASE)
#endif

#ifdef CONFIG_RX66T_QSPI
#  define RX66T_SPRI_IRQ        (RX66T_QSPI_IRQBASE)
#  define RX66T_SPTI_IRQ        (RX66T_QSPI_IRQBASE + 1)
#  define RX66T_SDHI_IRQBASE    (RX66T_QSPI_IRQBASE + 2)
#else
#  define RX66T_SDHI_IRQBASE    (RX66T_QSPI_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SDHI
#  define RX66T_SBFAI_IRQ        (RX66T_SDHI_IRQBASE)
#  define RX66T_MMCIF_IRQBASE    (RX66T_SDHI_IRQBASE + 1)
#else
#  define RX66T_MMCIF_IRQBASE    (RX66T_SDHI_IRQBASE)
#endif

#ifdef CONFIG_RX66T_MMCIF
#  define RX66T_MBFAI_IRQ        (RX66T_MMCIF_IRQBASE)
#  define RX66T_RIIC1_IRQBASE    (RX66T_MMCIF_IRQBASE + 1)
#else
#  define RX66T_RIIC1_IRQBASE    (RX66T_MMCIF_IRQBASE)
#endif

#ifdef CONFIG_RX66T_RIIC1
#  define RX66T_RIIC1_RXI1_IRQ  (RX66T_RIIC1_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_RIIC1_TXI1_IRQ  (RX66T_RIIC1_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_RIIC0_IRQBASE   (RX66T_RIIC1_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_RIIC0_IRQBASE   (RX66T_RIIC1_IRQBASE)
#endif

#ifdef CONFIG_RX66T_RIIC0
#  define RX66T_RIIC0_RXI0_IRQ  (RX66T_RIIC0_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_RIIC0_TXI0_IRQ  (RX66T_RIIC0_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_RIIC2_IRQBASE   (RX66T_RIIC0_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_RIIC2_IRQBASE   (RX66T_RIIC0_IRQBASE)
#endif

#ifdef CONFIG_RX66T_RIIC2
#  define RX66T_RIIC2_RXI2_IRQ  (RX66T_RIIC2_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_RIIC2_TXI2_IRQ  (RX66T_RIIC2_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_SCI0_IRQBASE    (RX66T_RIIC2_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_SCI0_IRQBASE    (RX66T_RIIC2_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SCI0
#  define RX66T_RXI0_IRQ        (RX66T_SCI0_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI0_IRQ        (RX66T_SCI0_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_ERI0_IRQ        (RX66T_SCI0_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI0_IRQ        (RX66T_SCI0_IRQBASE + RX_TEI_IRQ_OFFSET)
#  define RX66T_SCI1_IRQBASE    (RX66T_SCI0_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_SCI1_IRQBASE    (RX66T_SCI0_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SCI1
#  define RX66T_RXI1_IRQ        (RX66T_SCI1_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI1_IRQ        (RX66T_SCI1_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_ERI1_IRQ        (RX66T_SCI1_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI1_IRQ        (RX66T_SCI1_IRQBASE + RX_TEI_IRQ_OFFSET)
#  define RX66T_SCI2_IRQBASE    (RX66T_SCI1_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_SCI2_IRQBASE    (RX66T_SCI1_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SCI2
#  define RX66T_RXI2_IRQ        (RX66T_SCI2_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI2_IRQ        (RX66T_SCI2_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_ERI2_IRQ        (RX66T_SCI2_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI2_IRQ        (RX66T_SCI2_IRQBASE + RX_TEI_IRQ_OFFSET)
#  define RX66T_ICU_IRQ_IRQBASE (RX66T_SCI2_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_ICU_IRQ_IRQBASE (RX66T_SCI2_IRQBASE)
#endif

#if defined(CONFIG_ICU) || defined(CONFIG_RX66T_ICU)
#  define RX66T_IRQ0_IRQ      (RX66T_ICU_IRQ_IRQBASE)
#  define RX66T_IRQ1_IRQ      (RX66T_ICU_IRQ_IRQBASE+1)
#  define RX66T_IRQ2_IRQ      (RX66T_ICU_IRQ_IRQBASE+2)
#  define RX66T_IRQ3_IRQ      (RX66T_ICU_IRQ_IRQBASE+3)
#  define RX66T_IRQ4_IRQ      (RX66T_ICU_IRQ_IRQBASE+4)
#  define RX66T_IRQ5_IRQ      (RX66T_ICU_IRQ_IRQBASE+5)
#  define RX66T_IRQ6_IRQ      (RX66T_ICU_IRQ_IRQBASE+6)
#  define RX66T_IRQ7_IRQ      (RX66T_ICU_IRQ_IRQBASE+7)
#  define RX66T_IRQ8_IRQ      (RX66T_ICU_IRQ_IRQBASE+8)
#  define RX66T_IRQ9_IRQ      (RX66T_ICU_IRQ_IRQBASE+9)
#  define RX66T_IRQ10_IRQ     (RX66T_ICU_IRQ_IRQBASE+10)
#  define RX66T_IRQ11_IRQ     (RX66T_ICU_IRQ_IRQBASE+11)
#  define RX66T_IRQ12_IRQ     (RX66T_ICU_IRQ_IRQBASE+12)
#  define RX66T_IRQ13_IRQ     (RX66T_ICU_IRQ_IRQBASE+13)
#  define RX66T_IRQ14_IRQ     (RX66T_ICU_IRQ_IRQBASE+14)
#  define RX66T_IRQ15_IRQ     (RX66T_ICU_IRQ_IRQBASE+15)
#  define RX66T_SCI3_IRQBASE  (RX66T_ICU_IRQ_IRQBASE+16)
#else
#  define RX66T_SCI3_IRQBASE  (RX66T_ICU_IRQ_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SCI3
#  define RX66T_RXI3_IRQ        (RX66T_SCI3_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI3_IRQ        (RX66T_SCI3_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_ERI3_IRQ        (RX66T_SCI3_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI3_IRQ        (RX66T_SCI3_IRQBASE + RX_TEI_IRQ_OFFSET)
#  define RX66T_SCI4_IRQBASE    (RX66T_SCI3_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_SCI4_IRQBASE    (RX66T_SCI3_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SCI4
#  define RX66T_RXI4_IRQ        (RX66T_SCI4_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI4_IRQ        (RX66T_SCI4_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_ERI4_IRQ        (RX66T_SCI4_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI4_IRQ        (RX66T_SCI4_IRQBASE + RX_TEI_IRQ_OFFSET)
#  define RX66T_SCI5_IRQBASE    (RX66T_SCI4_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_SCI5_IRQBASE    (RX66T_SCI4_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SCI5
#  define RX66T_RXI5_IRQ        (RX66T_SCI5_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI5_IRQ        (RX66T_SCI5_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_ERI5_IRQ        (RX66T_SCI5_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI5_IRQ        (RX66T_SCI5_IRQBASE + RX_TEI_IRQ_OFFSET)
#  define RX66T_SCI6_IRQBASE    (RX66T_SCI5_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_SCI6_IRQBASE    (RX66T_SCI5_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SCI6
#  define RX66T_RXI6_IRQ        (RX66T_SCI6_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI6_IRQ        (RX66T_SCI6_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_ERI6_IRQ        (RX66T_SCI6_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI6_IRQ        (RX66T_SCI6_IRQBASE + RX_TEI_IRQ_OFFSET)
#  define RX66T_LVD1_IRQBASE    (RX66T_SCI6_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_LVD1_IRQBASE    (RX66T_SCI6_IRQBASE)
#endif

#ifdef CONFIG_RX66T_LVD1
#  define RX66T_LVD1_IRQ        (RX66T_LVD1_IRQBASE)
#  define RX66T_LVD2_IRQBASE    (RX66T_LVD1_IRQBASE + 1)
#else
#  define RX66T_LVD2_IRQBASE    (RX66T_LVD1_IRQBASE)
#endif

#ifdef CONFIG_RX66T_LVD2
#  define RX66T_LVD2_IRQ           (RX66T_LVD2_IRQBASE)
#  define RX66T_USB0_R0_IRQBASE    (RX66T_LVD2_IRQBASE + 1)
#else
#  define RX66T_USB0_R0_IRQBASE    (RX66T_LVD2_IRQBASE)
#endif

#ifdef CONFIG_RX66T_USB0_R0
#  define RX66T_USBR0_IRQ       (RX66T_USB0_R0_IRQBASE)
#  define RX66T_RTC_IRQBASE     (RX66T_USB0_R0_IRQBASE)
#else
#  define RX66T_RTC_IRQBASE     (RX66T_USB0_R0_IRQBASE)
#endif

#ifdef CONFIG_RX66T_RTC
#  define RX66T_ALM_IRQ         (RX66T_RTC_IRQBASE)
#  define RX66T_PRD_IRQ         (RX66T_RTC_IRQBASE + 1)
#  define RX66T_IWDT_IRQBASE    (RX66T_RTC_IRQBASE + 2)
#else
#  define RX66T_IWDT_IRQBASE    (RX66T_RTC_IRQBASE)
#endif

#ifdef CONFIG_RX66T_IWDT
#  define RX66T_IWUNI_IRQ        (RX66T_IWDT_IRQBASE)
#  define RX66T_WDT_IRQBASE      (RX66T_IWDT_IRQBASE + 1)
#else
#  define RX66T_WDT_IRQBASE      (RX66T_IWDT_IRQBASE)
#endif

#ifdef CONFIG_RX66T_WDT
#  define RX66T_WUNI_IRQ        (RX66T_WDT_IRQBASE)
#  define RX66T_PDC_IRQBASE     (RX66T_WDT_IRQBASE + 1)
#else
#  define RX66T_PDC_IRQBASE     (RX66T_WDT_IRQBASE)
#endif

#ifdef CONFIG_RX66T_PDC
#  define RX66T_PCDFI_IRQ       (RX66T_PDC_IRQBASE)
#  define RX66T_SCI7_IRQBASE    (RX66T_PDC_IRQBASE + 1)
#else
#  define RX66T_SCI7_IRQBASE    (RX66T_PDC_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SCI7
#  define RX66T_RXI7_IRQ        (RX66T_SCI7_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI7_IRQ        (RX66T_SCI7_IRQBASE + RX_TXI_IRQ_OFFSET)
# ifdef USE_GROUP_IRQ
#  define RX66T_ERI7_IRQ        (RX66T_SCI7_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI7_IRQ        (RX66T_SCI7_IRQBASE + RX_TEI_IRQ_OFFSET)
# endif
#  define RX66T_SCI8_IRQBASE    (RX66T_SCI7_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_SCI8_IRQBASE    (RX66T_SCI7_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SCI8
#  define RX66T_RXI8_IRQ        (RX66T_SCI8_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI8_IRQ        (RX66T_SCI8_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_ERI8_IRQ        (RX66T_SCI8_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI8_IRQ        (RX66T_SCI8_IRQBASE + RX_TEI_IRQ_OFFSET)
#  define RX66T_SCI9_IRQBASE    (RX66T_SCI8_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_SCI9_IRQBASE    (RX66T_SCI8_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SCI9
#  define RX66T_RXI9_IRQ        (RX66T_SCI9_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI9_IRQ        (RX66T_SCI9_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_ERI9_IRQ        (RX66T_SCI9_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI9_IRQ        (RX66T_SCI9_IRQBASE + RX_TEI_IRQ_OFFSET)
#  define RX66T_SCI10_IRQBASE   (RX66T_SCI9_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_SCI10_IRQBASE   (RX66T_SCI9_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SCI10
#  define RX66T_RXI10_IRQ             (RX66T_SCI10_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI10_IRQ             (RX66T_SCI10_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_ERI10_IRQ             (RX66T_SCI10_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI10_IRQ             (RX66T_SCI10_IRQBASE + RX_TEI_IRQ_OFFSET)
#  define RX66T_IRQ_GROUPB_IRQBASE    (RX66T_SCI10_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_IRQ_GROUPB_IRQBASE    (RX66T_SCI10_IRQBASE)
#endif

#ifdef CONFIG_RX66T_IRQ_GROUP
#  define RX66T_GROUPBE0_IRQ  (RX66T_IRQ_GROUPB_IRQBASE)
#  define RX66T_GROUPBL2_IRQ  (RX66T_IRQ_GROUPB_IRQBASE + 1)
#  define RX66T_RSPI2_IRQBASE (RX66T_IRQ_GROUPB_IRQBASE + 2)
#else
#  define RX66T_RSPI2_IRQBASE (RX66T_IRQ_GROUPB_IRQBASE)
#endif

#ifdef CONFIG_RX66T_RSPI2
#  define RX66T_SPRI2_IRQ               (RX66T_RSPI2_IRQBASE)
#  define RX66T_SPTI2_IRQ               (RX66T_RSPI2_IRQBASE + 1)
#  define RX66T_IRQ_GROUPBL_IRQBASE     (RX66T_RSPI2_IRQBASE + 2)
#else
#  define RX66T_IRQ_GROUPBL_IRQBASE     (RX66T_RSPI2_IRQBASE)
#endif

#ifdef CONFIG_RX66T_IRQ_GROUP
#  define RX66T_GROUPBL0_IRQ  (RX66T_IRQ_GROUPBL_IRQBASE)
#  define RX66T_GROUPBL1_IRQ  (RX66T_IRQ_GROUPBL_IRQBASE + 1)
#  define RX66T_GROUPAL0_IRQ  (RX66T_IRQ_GROUPBL_IRQBASE + 2)
#  define RX66T_GROUPAL1_IRQ  (RX66T_IRQ_GROUPBL_IRQBASE + 3)
#  define RX66T_SCI11_IRQBASE (RX66T_IRQ_GROUPBL_IRQBASE + 4)
#else
#  define RX66T_SCI11_IRQBASE (RX66T_IRQ_GROUPBL_IRQBASE)
#endif


#ifdef CONFIG_RX66T_SCI11
#  define RX66T_RXI11_IRQ        (RX66T_SCI11_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI11_IRQ        (RX66T_SCI11_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_ERI11_IRQ        (RX66T_SCI11_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI11_IRQ        (RX66T_SCI11_IRQBASE + RX_TEI_IRQ_OFFSET)
#  define RX66T_SCI12_IRQBASE    (RX66T_SCI11_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_SCI12_IRQBASE    (RX66T_SCI11_IRQBASE)
#endif

#ifdef CONFIG_RX66T_SCI12
#  define RX66T_RXI12_IRQ        (RX66T_SCI12_IRQBASE + RX_RXI_IRQ_OFFSET)
#  define RX66T_TXI12_IRQ        (RX66T_SCI12_IRQBASE + RX_TXI_IRQ_OFFSET)
#  define RX66T_ERI12_IRQ        (RX66T_SCI12_IRQBASE + RX_ERI_IRQ_OFFSET)
#  define RX66T_TEI12_IRQ        (RX66T_SCI12_IRQBASE + RX_TEI_IRQ_OFFSET)
#  define RX66T_DMAC_IRQBASE     (RX66T_SCI12_IRQBASE + RX_SCI_NIRQS)
#else
#  define RX66T_DMAC_IRQBASE     (RX66T_SCI12_IRQBASE)
#endif

#ifdef CONFIG_RX66T_DMAC
#  define RX66T_DMAC0I_IRQ        (RX66T_DMAC_IRQBASE)
#  define RX66T_DMAC1I_IRQ        (RX66T_DMAC_IRQBASE + 1)
#  define RX66T_DMAC2I_IRQ        (RX66T_DMAC_IRQBASE + 2)
#  define RX66T_DMAC3I_IRQ        (RX66T_DMAC_IRQBASE + 3)
#  define RX66T_DMAC74I_IRQ       (RX66T_DMAC_IRQBASE + 4)
#  define RX66T_OST_IRQBASE       (RX66T_DMAC_IRQBASE + 5)
#else
#  define RX66T_OST_IRQBASE       (RX66T_DMAC_IRQBASE)
#endif

#ifdef CONFIG_RX66T_OST
#  define RX66T_OSTD1_IRQ         (RX66T_OST_IRQBASE)
#  define RX66T_EXDMAC_IRQBASE    (RX66T_OST_IRQBASE + 1)
#else
#  define RX66T_EXDMAC_IRQBASE    (RX66T_OST_IRQBASE)
#endif

#ifdef CONFIG_RX66T_EXDMAC
#  define RX66T_EXDMAC0I_IRQ         (RX66T_EXDMAC_IRQBASE)
#  define RX66T_EXDMAC1I_IRQ         (RX66T_EXDMAC_IRQBASE + 1)
#  define RX66T_PERIB_IRQBASE        (RX66T_EXDMAC_IRQBASE + 2)
#else
#  define RX66T_PERIB_IRQBASE        (RX66T_EXDMAC_IRQBASE)
#endif

#  ifdef CONFIG_RX66T_PERIB
#  define RX66T_INTB128_IRQ          (RX66T_PERIB_IRQBASE)
#  define RX66T_INTB129_IRQ          (RX66T_PERIB_IRQBASE + 1)
#  define RX66T_INTB130_IRQ          (RX66T_PERIB_IRQBASE + 2)
#  define RX66T_INTB131_IRQ          (RX66T_PERIB_IRQBASE + 3)
#  define RX66T_INTB132_IRQ          (RX66T_PERIB_IRQBASE + 4)
#  define RX66T_INTB133_IRQ          (RX66T_PERIB_IRQBASE + 5)
#  define RX66T_INTB134_IRQ          (RX66T_PERIB_IRQBASE + 6)
#  define RX66T_INTB135_IRQ          (RX66T_PERIB_IRQBASE + 7)
#  define RX66T_INTB136_IRQ          (RX66T_PERIB_IRQBASE + 8)
#  define RX66T_INTB137_IRQ          (RX66T_PERIB_IRQBASE + 9)
#  define RX66T_INTB138_IRQ          (RX66T_PERIB_IRQBASE + 10)
#  define RX66T_INTB139_IRQ          (RX66T_PERIB_IRQBASE + 11)
#  define RX66T_INTB140_IRQ          (RX66T_PERIB_IRQBASE + 12)
#  define RX66T_INTB141_IRQ          (RX66T_PERIB_IRQBASE + 13)
#  define RX66T_INTB142_IRQ          (RX66T_PERIB_IRQBASE + 14)
#  define RX66T_INTB143_IRQ          (RX66T_PERIB_IRQBASE + 15)
#  define RX66T_INTB144_IRQ          (RX66T_PERIB_IRQBASE + 16)
#  define RX66T_INTB145_IRQ          (RX66T_PERIB_IRQBASE + 17)
#  define RX66T_INTB146_IRQ          (RX66T_PERIB_IRQBASE + 18)
#  define RX66T_INTB147_IRQ          (RX66T_PERIB_IRQBASE + 19)
#  define RX66T_INTB148_IRQ          (RX66T_PERIB_IRQBASE + 20)
#  define RX66T_INTB149_IRQ          (RX66T_PERIB_IRQBASE + 21)
#  define RX66T_INTB150_IRQ          (RX66T_PERIB_IRQBASE + 22)
#  define RX66T_INTB151_IRQ          (RX66T_PERIB_IRQBASE + 23)
#  define RX66T_INTB152_IRQ          (RX66T_PERIB_IRQBASE + 24)
#  define RX66T_INTB153_IRQ          (RX66T_PERIB_IRQBASE + 25)
#  define RX66T_INTB154_IRQ          (RX66T_PERIB_IRQBASE + 26)
#  define RX66T_INTB155_IRQ          (RX66T_PERIB_IRQBASE + 27)
#  define RX66T_INTB156_IRQ          (RX66T_PERIB_IRQBASE + 28)
#  define RX66T_INTB157_IRQ          (RX66T_PERIB_IRQBASE + 29)
#  define RX66T_INTB158_IRQ          (RX66T_PERIB_IRQBASE + 30)
#  define RX66T_INTB159_IRQ          (RX66T_PERIB_IRQBASE + 31)
#  define RX66T_INTB160_IRQ          (RX66T_PERIB_IRQBASE + 32)
#  define RX66T_INTB161_IRQ          (RX66T_PERIB_IRQBASE + 33)
#  define RX66T_INTB162_IRQ          (RX66T_PERIB_IRQBASE + 34)
#  define RX66T_INTB163_IRQ          (RX66T_PERIB_IRQBASE + 35)
#  define RX66T_INTB164_IRQ          (RX66T_PERIB_IRQBASE + 36)
#  define RX66T_INTB165_IRQ          (RX66T_PERIB_IRQBASE + 37)
#  define RX66T_INTB166_IRQ          (RX66T_PERIB_IRQBASE + 38)
#  define RX66T_INTB167_IRQ          (RX66T_PERIB_IRQBASE + 39)
#  define RX66T_INTB168_IRQ          (RX66T_PERIB_IRQBASE + 40)
#  define RX66T_INTB169_IRQ          (RX66T_PERIB_IRQBASE + 41)
#  define RX66T_INTB170_IRQ          (RX66T_PERIB_IRQBASE + 42)
#  define RX66T_INTB171_IRQ          (RX66T_PERIB_IRQBASE + 43)
#  define RX66T_INTB172_IRQ          (RX66T_PERIB_IRQBASE + 44)
#  define RX66T_INTB173_IRQ          (RX66T_PERIB_IRQBASE + 45)
#  define RX66T_INTB174_IRQ          (RX66T_PERIB_IRQBASE + 46)
#  define RX66T_INTB175_IRQ          (RX66T_PERIB_IRQBASE + 47)
#  define RX66T_INTB176_IRQ          (RX66T_PERIB_IRQBASE + 48)
#  define RX66T_INTB177_IRQ          (RX66T_PERIB_IRQBASE + 49)
#  define RX66T_INTB178_IRQ          (RX66T_PERIB_IRQBASE + 50)
#  define RX66T_INTB179_IRQ          (RX66T_PERIB_IRQBASE + 51)
#  define RX66T_INTB180_IRQ          (RX66T_PERIB_IRQBASE + 52)
#  define RX66T_INTB181_IRQ          (RX66T_PERIB_IRQBASE + 53)
#  define RX66T_INTB182_IRQ          (RX66T_PERIB_IRQBASE + 54)
#  define RX66T_INTB183_IRQ          (RX66T_PERIB_IRQBASE + 55)
#  define RX66T_INTB184_IRQ          (RX66T_PERIB_IRQBASE + 56)
#  define RX66T_INTB185_IRQ          (RX66T_PERIB_IRQBASE + 57)
#  define RX66T_INTB186_IRQ          (RX66T_PERIB_IRQBASE + 58)
#  define RX66T_INTB187_IRQ          (RX66T_PERIB_IRQBASE + 59)
#  define RX66T_INTB188_IRQ          (RX66T_PERIB_IRQBASE + 60)
#  define RX66T_INTB189_IRQ          (RX66T_PERIB_IRQBASE + 61)
#  define RX66T_INTB190_IRQ          (RX66T_PERIB_IRQBASE + 62)
#  define RX66T_INTB191_IRQ          (RX66T_PERIB_IRQBASE + 63)
#  define RX66T_INTB192_IRQ          (RX66T_PERIB_IRQBASE + 64)
#  define RX66T_INTB193_IRQ          (RX66T_PERIB_IRQBASE + 65)
#  define RX66T_INTB194_IRQ          (RX66T_PERIB_IRQBASE + 66)
#  define RX66T_INTB195_IRQ          (RX66T_PERIB_IRQBASE + 67)
#  define RX66T_INTB196_IRQ          (RX66T_PERIB_IRQBASE + 68)
#  define RX66T_INTB197_IRQ          (RX66T_PERIB_IRQBASE + 69)
#  define RX66T_INTB198_IRQ          (RX66T_PERIB_IRQBASE + 70)
#  define RX66T_INTB199_IRQ          (RX66T_PERIB_IRQBASE + 71)
#  define RX66T_INTB200_IRQ          (RX66T_PERIB_IRQBASE + 72)
#  define RX66T_INTB201_IRQ          (RX66T_PERIB_IRQBASE + 73)
#  define RX66T_INTB202_IRQ          (RX66T_PERIB_IRQBASE + 74)
#  define RX66T_INTB203_IRQ          (RX66T_PERIB_IRQBASE + 75)
#  define RX66T_INTB204_IRQ          (RX66T_PERIB_IRQBASE + 76)
#  define RX66T_INTB205_IRQ          (RX66T_PERIB_IRQBASE + 77)
#  define RX66T_INTB206_IRQ          (RX66T_PERIB_IRQBASE + 78)
#  define RX66T_INTB207_IRQ          (RX66T_PERIB_IRQBASE + 79)
#  define RX66T_PERIA_IRQBASE        (RX66T_PERIB_IRQBASE + 80)
#else
#  define RX66T_PERIA_IRQBASE        (RX66T_PERIB_IRQBASE)
#endif

#ifdef CONFIG_RX66T_PERIA
#  define RX66T_INTA208_IRQ          (RX66T_PERIA_IRQBASE)
#  define RX66T_INTA209_IRQ          (RX66T_PERIA_IRQBASE + 1)
#  define RX66T_INTA210_IRQ          (RX66T_PERIA_IRQBASE + 2)
#  define RX66T_INTA211_IRQ          (RX66T_PERIA_IRQBASE + 3)
#  define RX66T_INTA212_IRQ          (RX66T_PERIA_IRQBASE + 4)
#  define RX66T_INTA213_IRQ          (RX66T_PERIA_IRQBASE + 5)
#  define RX66T_INTA214_IRQ          (RX66T_PERIA_IRQBASE + 6)
#  define RX66T_INTA215_IRQ          (RX66T_PERIA_IRQBASE + 7)
#  define RX66T_INTA216_IRQ          (RX66T_PERIA_IRQBASE + 8)
#  define RX66T_INTA217_IRQ          (RX66T_PERIA_IRQBASE + 9)
#  define RX66T_INTA218_IRQ          (RX66T_PERIA_IRQBASE + 10)
#  define RX66T_INTA219_IRQ          (RX66T_PERIA_IRQBASE + 11)
#  define RX66T_INTA220_IRQ          (RX66T_PERIA_IRQBASE + 12)
#  define RX66T_INTA221_IRQ          (RX66T_PERIA_IRQBASE + 13)
#  define RX66T_INTA222_IRQ          (RX66T_PERIA_IRQBASE + 14)
#  define RX66T_INTA223_IRQ          (RX66T_PERIA_IRQBASE + 15)
#  define RX66T_INTA224_IRQ          (RX66T_PERIA_IRQBASE + 16)
#  define RX66T_INTA225_IRQ          (RX66T_PERIA_IRQBASE + 17)
#  define RX66T_INTA226_IRQ          (RX66T_PERIA_IRQBASE + 18)
#  define RX66T_INTA227_IRQ          (RX66T_PERIA_IRQBASE + 19)
#  define RX66T_INTA228_IRQ          (RX66T_PERIA_IRQBASE + 20)
#  define RX66T_INTA229_IRQ          (RX66T_PERIA_IRQBASE + 21)
#  define RX66T_INTA230_IRQ          (RX66T_PERIA_IRQBASE + 22)
#  define RX66T_INTA231_IRQ          (RX66T_PERIA_IRQBASE + 23)
#  define RX66T_INTA232_IRQ          (RX66T_PERIA_IRQBASE + 24)
#  define RX66T_INTA233_IRQ          (RX66T_PERIA_IRQBASE + 25)
#  define RX66T_INTA234_IRQ          (RX66T_PERIA_IRQBASE + 26)
#  define RX66T_INTA235_IRQ          (RX66T_PERIA_IRQBASE + 27)
#  define RX66T_INTA236_IRQ          (RX66T_PERIA_IRQBASE + 28)
#  define RX66T_INTA237_IRQ          (RX66T_PERIA_IRQBASE + 29)
#  define RX66T_INTA238_IRQ          (RX66T_PERIA_IRQBASE + 30)
#  define RX66T_INTA239_IRQ          (RX66T_PERIA_IRQBASE + 31)
#  define RX66T_INTA240_IRQ          (RX66T_PERIA_IRQBASE + 32)
#  define RX66T_INTA241_IRQ          (RX66T_PERIA_IRQBASE + 33)
#  define RX66T_INTA242_IRQ          (RX66T_PERIA_IRQBASE + 34)
#  define RX66T_INTA243_IRQ          (RX66T_PERIA_IRQBASE + 35)
#  define RX66T_INTA244_IRQ          (RX66T_PERIA_IRQBASE + 36)
#  define RX66T_INTA245_IRQ          (RX66T_PERIA_IRQBASE + 37)
#  define RX66T_INTA246_IRQ          (RX66T_PERIA_IRQBASE + 38)
#  define RX66T_INTA247_IRQ          (RX66T_PERIA_IRQBASE + 39)
#  define RX66T_INTA248_IRQ          (RX66T_PERIA_IRQBASE + 40)
#  define RX66T_INTA249_IRQ          (RX66T_PERIA_IRQBASE + 41)
#  define RX66T_INTA250_IRQ          (RX66T_PERIA_IRQBASE + 42)
#  define RX66T_INTA251_IRQ          (RX66T_PERIA_IRQBASE + 43)
#  define RX66T_INTA252_IRQ          (RX66T_PERIA_IRQBASE + 44)
#  define RX66T_INTA253_IRQ          (RX66T_PERIA_IRQBASE + 45)
#  define RX66T_INTA254_IRQ          (RX66T_PERIA_IRQBASE + 46)
#  define RX66T_INTA255_IRQ          (RX66T_PERIA_IRQBASE + 47)
#  define NR_IRQS                    (RX66T_PERIA_IRQBASE + 48)
#else
#  define NR_IRQS                    (RX66T_PERIA_IRQBASE)
#endif

/* IRQ Stack Frame Format.  The RX66T has a push down stack.  The PC
 * and SR are pushed by hardware at the time an IRQ is taken.
 */

/* Saved to the stacked by up_vector */

/* Vector table offets **************************************************************/

/* Trap instruction */
#  define RX66T_TRAP_VNDX      (0)
#  define RX66T_TRAP0_VNDX     (RX66T_TRAP_VNDX)
#  define RX66T_TRAP1_VNDX     (RX66T_TRAP_VNDX +  1)
#  define RX66T_TRAP2_VNDX     (RX66T_TRAP_VNDX +  2)
#  define RX66T_TRAP3_VNDX     (RX66T_TRAP_VNDX +  3)
#  define RX66T_TRAP4_VNDX     (RX66T_TRAP_VNDX +  4)
#  define RX66T_TRAP5_VNDX     (RX66T_TRAP_VNDX +  5)
#  define RX66T_TRAP6_VNDX     (RX66T_TRAP_VNDX +  6)
#  define RX66T_TRAP7_VNDX     (RX66T_TRAP_VNDX +  7)
#  define RX66T_TRAP8_VNDX     (RX66T_TRAP_VNDX +  8)
#  define RX66T_TRAP9_VNDX     (RX66T_TRAP_VNDX +  9)
#  define RX66T_TRAP10_VNDX    (RX66T_TRAP_VNDX + 10)
#  define RX66T_TRAP11_VNDX    (RX66T_TRAP_VNDX + 11)
#  define RX66T_TRAP12_VNDX    (RX66T_TRAP_VNDX + 12)
#  define RX66T_TRAP13_VNDX    (RX66T_TRAP_VNDX + 13)
#  define RX66T_TRAP14_VNDX    (RX66T_TRAP_VNDX + 14)
#  define RX66T_TRAP15_VNDX    (RX66T_TRAP_VNDX + 15)

/* Bus Error */
#  define RX66T_BUSERR_VNDX    (VECT_BSC_BUSERR)

/* RAM Error */
#  define RX66T_RAMERR_VNDX    (VECT_RAM_RAMERR)

 /* FIFERR Error */
# define RX66T_FIFERR_VNDX     (VECT_FCU_FIFERR)

/* FRDYI */
#  define RX66T_FRDYI_VNDX      (VECT_FCU_FRDYI)

 /* ICU Interrupts */
#  define RX66T_SWINT2_VNDX     (VECT_ICU_SWINT2)
#  define RX66T_SWINT_VNDX      (VECT_ICU_SWINT)
#  define RX66T_IRQ0_VNDX       (VECT_ICU_IRQ0)
#  define RX66T_IRQ1_VNDX       (VECT_ICU_IRQ1)
#  define RX66T_IRQ2_VNDX       (VECT_ICU_IRQ2)
#  define RX66T_IRQ3_VNDX       (VECT_ICU_IRQ3)
#  define RX66T_IRQ4_VNDX       (VECT_ICU_IRQ4)
#  define RX66T_IRQ5_VNDX       (VECT_ICU_IRQ5)
#  define RX66T_IRQ6_VNDX       (VECT_ICU_IRQ6)
#  define RX66T_IRQ7_VNDX       (VECT_ICU_IRQ7)
#  define RX66T_IRQ8_VNDX       (VECT_ICU_IRQ8)
#  define RX66T_IRQ9_VNDX       (VECT_ICU_IRQ9)
#  define RX66T_IRQ10_VNDX      (VECT_ICU_IRQ10)
#  define RX66T_IRQ11_VNDX      (VECT_ICU_IRQ11)
#  define RX66T_IRQ12_VNDX      (VECT_ICU_IRQ12)
#  define RX66T_IRQ13_VNDX      (VECT_ICU_IRQ13)
#  define RX66T_IRQ14_VNDX      (VECT_ICU_IRQ14)
#  define RX66T_IRQ15_VNDX      (VECT_ICU_IRQ15)
#  define RX66T_GROUPBE0_VNDX   (VECT_ICU_GROUPBE0)
#  define RX66T_GROUPBL0_VNDX   (VECT_ICU_GROUPBL0)
#  define RX66T_GROUPBL1_VNDX   (VECT_ICU_GROUPBL1)
#  define RX66T_GROUPBL2_VNDX   (VECT_ICU_GROUPBL2)
#  define RX66T_GROUPAL0_VNDX   (VECT_ICU_GROUPAL0)
#  define RX66T_GROUPAL1_VNDX   (VECT_ICU_GROUPAL1)

/* CMT Interrupts */
#  define  RX66T_CMI0_VNDX      (VECT_CMT0_CMI0)
#  define  RX66T_CMI1_VNDX      (VECT_CMT0_CMI1)
#  define  RX66T_CMWI0_VNDX     (VECT_CMT0_CMWI0)
#  define  RX66T_CMWI1_VNDX     (VECT_CMT0_CMWI1)

/* USB Interrupts */
#  define RX66T_D0FIFO0_VNDX    (VECT_USB0_D0FIFO0)
#  define RX66T_D1FIFO0_VNDX    (VECT_USB0_D1FIFO0)
#  define RX66T_USBR0_VNDX      (VECT_USB0_USBR0)

/* RSPI Interrupts */
#  define RX66T_SPRI0_VNDX      (VECT_RSPI0_SPRI0)
#  define RX66T_SPTI0_VNDX      (VECT_RSPI0_SPTI0)
#  define RX66T_SPRI1_VNDX      (VECT_RSPI1_SPRI1)
#  define RX66T_SPTI1_VNDX      (VECT_RSPI1_SPTI1)
#  define RX66T_SPRI2_VNDX      (VECT_RSPI2_SPRI2)
#  define RX66T_SPTI2_VNDX      (VECT_RSPI2_SPTI2)

/* QSPI Interrupts */
#  define RX66T_SPRI_VNDX       (VECT_QSPI_SPRI)
#  define RX66T_SPTI_VNDX       (VECT_QSPI_SPTI)

/* SDHI MMC Interrupts */
#  define RX66T_SBFAI_VNDX      (VECT_SDHI_SBFAI)
#  define RX66T_MBFAI_VNDX      (VECT_MMCIF_MBFAI)

 /* RIIC Interrupts */
#  define RX66T_RIIC0_EEI0_VNDX       (VECT_ICU_GROUPBL1)
#  define RX66T_RIIC0_RXI0_VNDX       (VECT_RIIC0_RXI0)
#  define RX66T_RIIC0_TXI0_VNDX       (VECT_RIIC0_TXI0)
#  define RX66T_RIIC0_TEI0_VNDX       (VECT_ICU_GROUPBL1)

#  define RX66T_RIIC1_EEI1_VNDX       (VECT_ICU_GROUPBL1)
#  define RX66T_RIIC1_RXI1_VNDX       (VECT_RIIC1_RXI1)
#  define RX66T_RIIC1_TXI1_VNDX       (VECT_RIIC1_TXI1)
#  define RX66T_RIIC1_TEI1_VNDX       (VECT_ICU_GROUPBL1)

#  define RX66T_RIIC2_EEI2_VNDX       (VECT_ICU_GROUPBL1)
#  define RX66T_RIIC2_RXI2_VNDX       (VECT_RIIC2_RXI2)
#  define RX66T_RIIC2_TXI2_VNDX       (VECT_RIIC2_TXI2)
#  define RX66T_RIIC2_TEI2_VNDX       (VECT_ICU_GROUPBL1)

/* SCI Interrupts */
#  define RX66T_ERI0_VNDX       (VECT_ICU_GROUPBL0)
#  define RX66T_RXI0_VNDX       (VECT_SCI0_RXI0)
#  define RX66T_TXI0_VNDX       (VECT_SCI0_TXI0)
#  define RX66T_TEI0_VNDX       (VECT_ICU_GROUPBL0)

#  define RX66T_ERI1_VNDX       (VECT_ICU_GROUPBL0)
#  define RX66T_RXI1_VNDX       (VECT_SCI1_RXI1)
#  define RX66T_TXI1_VNDX       (VECT_SCI1_TXI1)
#  define RX66T_TEI1_VNDX       (VECT_ICU_GROUPBL0)

#  define RX66T_ERI2_VNDX       (VECT_ICU_GROUPBL0)
#  define RX66T_RXI2_VNDX       (VECT_SCI2_RXI2)
#  define RX66T_TXI2_VNDX       (VECT_SCI2_TXI2)
#  define RX66T_TEI2_VNDX       (VECT_ICU_GROUPBL0)

#  define RX66T_ERI3_VNDX       (VECT_ICU_GROUPBL0)
#  define RX66T_RXI3_VNDX       (VECT_SCI3_RXI3)
#  define RX66T_TXI3_VNDX       (VECT_SCI3_TXI3)
#  define RX66T_TEI3_VNDX       (VECT_ICU_GROUPBL0)

#  define RX66T_ERI4_VNDX       (VECT_ICU_GROUPBL0)
#  define RX66T_RXI4_VNDX       (VECT_SCI4_RXI4)
#  define RX66T_TXI4_VNDX       (VECT_SCI4_TXI4)
#  define RX66T_TEI4_VNDX       (VECT_ICU_GROUPBL0)

#  define RX66T_ERI5_VNDX       (VECT_ICU_GROUPBL0)
#  define RX66T_RXI5_VNDX       (VECT_SCI5_RXI5)
#  define RX66T_TXI5_VNDX       (VECT_SCI5_TXI5)
#  define RX66T_TEI5_VNDX       (VECT_ICU_GROUPBL0)

#  define RX66T_ERI6_VNDX       (VECT_ICU_GROUPBL0)
#  define RX66T_RXI6_VNDX       (VECT_SCI6_RXI6)
#  define RX66T_TXI6_VNDX       (VECT_SCI6_TXI6)
#  define RX66T_TEI6_VNDX       (VECT_ICU_GROUPBL0)

#  define RX66T_ERI7_VNDX       (VECT_ICU_GROUPBL0)
#  define RX66T_RXI7_VNDX       (VECT_SCI7_RXI7)
#  define RX66T_TXI7_VNDX       (VECT_SCI7_TXI7)
#  define RX66T_TEI7_VNDX       (VECT_ICU_GROUPBL0)

#  define RX66T_ERI8_VNDX       (VECT_ICU_GROUPBL1)
#  define RX66T_RXI8_VNDX       (VECT_SCI8_RXI8)
#  define RX66T_TXI8_VNDX       (VECT_SCI8_TXI8)
#  define RX66T_TEI8_VNDX       (VECT_ICU_GROUPBL1)

#  define RX66T_ERI9_VNDX       (VECT_ICU_GROUPBL1)
#  define RX66T_RXI9_VNDX       (VECT_SCI9_RXI9)
#  define RX66T_TXI9_VNDX       (VECT_SCI9_TXI9)
#  define RX66T_TEI9_VNDX       (VECT_ICU_GROUPBL1)

#  define RX66T_ERI10_VNDX       (VECT_ICU_GROUPAL0)
#  define RX66T_RXI10_VNDX       (VECT_SCI10_RXI10)
#  define RX66T_TXI10_VNDX       (VECT_SCI10_TXI10)
#  define RX66T_TEI10_VNDX       (VECT_ICU_GROUPAL0)

#  define RX66T_ERI11_VNDX       (VECT_ICU_GROUPAL0)
#  define RX66T_RXI11_VNDX       (VECT_SCI11_RXI11)
#  define RX66T_TXI11_VNDX       (VECT_SCI11_TXI11)
#  define RX66T_TEI11_VNDX       (VECT_ICU_GROUPAL0)

#  define RX66T_ERI12_VNDX       (VECT_ICU_GROUPBL0)
#  define RX66T_RXI12_VNDX       (VECT_SCI12_RXI12)
#  define RX66T_TXI12_VNDX       (VECT_SCI12_TXI12)
#  define RX66T_TEI12_VNDX       (VECT_ICU_GROUPBL0)

/* LVD Interrupts */
#  define RX66T_LVD1_VNDX        (VECT_LVD1_LVD1)
#  define RX66T_LVD2_VNDX        (VECT_LVD2_LVD2)

/* RTC Interrupts */
#  define RX66T_ALM_VNDX         (VECT_RTC_ALM)
#  define RX66T_PRD_VNDX         (VECT_RTC_PRD)

/* WDT Interrupts */
#  define RX66T_IWUNI_VNDX        (VECT_IWDT_IWUNI)
#  define RX66T_WUNI_VNDX         (VECT_WDT_WUNI)

/* PDC Interrupts */
#  define RX66T_PCDFI_VNDX        (VECT_PDC_PCDFI)

/* DMAC Interrupts */
#  define RX66T_DMAC0I_VNDX       (VECT_DMAC_DMAC0I)
#  define RX66T_DMAC1I_VNDX       (VECT_DMAC_DMAC1I)
#  define RX66T_DMAC2I_VNDX       (VECT_DMAC_DMAC2I)
#  define RX66T_DMAC3I_VNDX       (VECT_DMAC_DMAC3I)
#  define RX66T_DMAC74I_VNDX      (VECT_DMAC_DMAC74I)

/*OST Interrupts */
#  define RX66T_OSTDI_VNDX           (VECT_OST_OSTDI)

/* EXDMAC Interrupts */
#  define RX66T_EXDMAC0I_VNDX        (VECT_EXDMAC_EXDMAC0I)
#  define RX66T_EXDMAC1I_VNDX        (VECT_EXDMAC_EXDMAC1I)


/* PERIB Interrupts */
#  define RX66T_INTB128_VNDX         (VECT_PERIB_INTB128)
#  define RX66T_INTB129_VNDX         (VECT_PERIB_INTB129)
#  define RX66T_INTB130_VNDX         (VECT_PERIB_INTB130)
#  define RX66T_INTB131_VNDX         (VECT_PERIB_INTB131)
#  define RX66T_INTB132_VNDX         (VECT_PERIB_INTB132)
#  define RX66T_INTB133_VNDX         (VECT_PERIB_INTB133)
#  define RX66T_INTB134_VNDX         (VECT_PERIB_INTB134)
#  define RX66T_INTB135_VNDX         (VECT_PERIB_INTB135)
#  define RX66T_INTB136_VNDX         (VECT_PERIB_INTB136)
#  define RX66T_INTB137_VNDX         (VECT_PERIB_INTB137)
#  define RX66T_INTB138_VNDX         (VECT_PERIB_INTB138)
#  define RX66T_INTB139_VNDX         (VECT_PERIB_INTB139)
#  define RX66T_INTB140_VNDX         (VECT_PERIB_INTB140)
#  define RX66T_INTB141_VNDX         (VECT_PERIB_INTB141)
#  define RX66T_INTB142_VNDX         (VECT_PERIB_INTB142)
#  define RX66T_INTB143_VNDX         (VECT_PERIB_INTB143)
#  define RX66T_INTB144_VNDX         (VECT_PERIB_INTB144)
#  define RX66T_INTB145_VNDX         (VECT_PERIB_INTB145)
#  define RX66T_INTB146_VNDX         (VECT_PERIB_INTB146)
#  define RX66T_INTB147_VNDX         (VECT_PERIB_INTB147)
#  define RX66T_INTB148_VNDX         (VECT_PERIB_INTB148)
#  define RX66T_INTB149_VNDX         (VECT_PERIB_INTB149)
#  define RX66T_INTB150_VNDX         (VECT_PERIB_INTB150)
#  define RX66T_INTB151_VNDX         (VECT_PERIB_INTB151)
#  define RX66T_INTB152_VNDX         (VECT_PERIB_INTB152)
#  define RX66T_INTB153_VNDX         (VECT_PERIB_INTB153)
#  define RX66T_INTB154_VNDX         (VECT_PERIB_INTB154)
#  define RX66T_INTB155_VNDX         (VECT_PERIB_INTB155)
#  define RX66T_INTB156_VNDX         (VECT_PERIB_INTB156)
#  define RX66T_INTB157_VNDX         (VECT_PERIB_INTB157)
#  define RX66T_INTB158_VNDX         (VECT_PERIB_INTB158)
#  define RX66T_INTB159_VNDX         (VECT_PERIB_INTB159)
#  define RX66T_INTB160_VNDX         (VECT_PERIB_INTB160)
#  define RX66T_INTB161_VNDX         (VECT_PERIB_INTB161)
#  define RX66T_INTB162_VNDX         (VECT_PERIB_INTB162)
#  define RX66T_INTB163_VNDX         (VECT_PERIB_INTB163)
#  define RX66T_INTB164_VNDX         (VECT_PERIB_INTB164)
#  define RX66T_INTB165_VNDX         (VECT_PERIB_INTB165)
#  define RX66T_INTB166_VNDX         (VECT_PERIB_INTB166)
#  define RX66T_INTB167_VNDX         (VECT_PERIB_INTB167)
#  define RX66T_INTB168_VNDX         (VECT_PERIB_INTB168)
#  define RX66T_INTB169_VNDX         (VECT_PERIB_INTB169)
#  define RX66T_INTB170_VNDX         (VECT_PERIB_INTB170)
#  define RX66T_INTB171_VNDX         (VECT_PERIB_INTB171)
#  define RX66T_INTB172_VNDX         (VECT_PERIB_INTB172)
#  define RX66T_INTB173_VNDX         (VECT_PERIB_INTB173)
#  define RX66T_INTB174_VNDX         (VECT_PERIB_INTB174)
#  define RX66T_INTB175_VNDX         (VECT_PERIB_INTB175)
#  define RX66T_INTB176_VNDX         (VECT_PERIB_INTB176)
#  define RX66T_INTB177_VNDX         (VECT_PERIB_INTB177)
#  define RX66T_INTB178_VNDX         (VECT_PERIB_INTB178)
#  define RX66T_INTB179_VNDX         (VECT_PERIB_INTB179)
#  define RX66T_INTB180_VNDX         (VECT_PERIB_INTB180)
#  define RX66T_INTB181_VNDX         (VECT_PERIB_INTB181)
#  define RX66T_INTB182_VNDX         (VECT_PERIB_INTB182)
#  define RX66T_INTB183_VNDX         (VECT_PERIB_INTB183)
#  define RX66T_INTB184_VNDX         (VECT_PERIB_INTB184)
#  define RX66T_INTB185_VNDX         (VECT_PERIB_INTB185)
#  define RX66T_INTB186_VNDX         (VECT_PERIB_INTB186)
#  define RX66T_INTB187_VNDX         (VECT_PERIB_INTB187)
#  define RX66T_INTB188_VNDX         (VECT_PERIB_INTB188)
#  define RX66T_INTB189_VNDX         (VECT_PERIB_INTB189)
#  define RX66T_INTB190_VNDX         (VECT_PERIB_INTB190)
#  define RX66T_INTB191_VNDX         (VECT_PERIB_INTB191)
#  define RX66T_INTB192_VNDX         (VECT_PERIB_INTB192)
#  define RX66T_INTB193_VNDX         (VECT_PERIB_INTB193)
#  define RX66T_INTB194_VNDX         (VECT_PERIB_INTB194)
#  define RX66T_INTB195_VNDX         (VECT_PERIB_INTB195)
#  define RX66T_INTB196_VNDX         (VECT_PERIB_INTB196)
#  define RX66T_INTB197_VNDX         (VECT_PERIB_INTB197)
#  define RX66T_INTB198_VNDX         (VECT_PERIB_INTB198)
#  define RX66T_INTB199_VNDX         (VECT_PERIB_INTB199)
#  define RX66T_INTB200_VNDX         (VECT_PERIB_INTB200)
#  define RX66T_INTB201_VNDX         (VECT_PERIB_INTB201)
#  define RX66T_INTB202_VNDX         (VECT_PERIB_INTB202)
#  define RX66T_INTB203_VNDX         (VECT_PERIB_INTB203)
#  define RX66T_INTB204_VNDX         (VECT_PERIB_INTB204)
#  define RX66T_INTB205_VNDX         (VECT_PERIB_INTB205)
#  define RX66T_INTB206_VNDX         (VECT_PERIB_INTB206)
#  define RX66T_INTB207_VNDX         (VECT_PERIB_INTB207)

/*PERIA Interrupts */
#  define RX66T_INTA208_VNDX         (VECT_PERIA_INTA208)
#  define RX66T_INTA209_VNDX         (VECT_PERIA_INTA209)
#  define RX66T_INTA210_VNDX         (VECT_PERIA_INTA210)
#  define RX66T_INTA211_VNDX         (VECT_PERIA_INTA211)
#  define RX66T_INTA212_VNDX         (VECT_PERIA_INTA212)
#  define RX66T_INTA213_VNDX         (VECT_PERIA_INTA213)
#  define RX66T_INTA214_VNDX         (VECT_PERIA_INTA214)
#  define RX66T_INTA215_VNDX         (VECT_PERIA_INTA215)
#  define RX66T_INTA216_VNDX         (VECT_PERIA_INTA216)
#  define RX66T_INTA217_VNDX         (VECT_PERIA_INTA217)
#  define RX66T_INTA218_VNDX         (VECT_PERIA_INTA218)
#  define RX66T_INTA219_VNDX         (VECT_PERIA_INTA219)
#  define RX66T_INTA220_VNDX         (VECT_PERIA_INTA220)
#  define RX66T_INTA221_VNDX         (VECT_PERIA_INTA221)
#  define RX66T_INTA222_VNDX         (VECT_PERIA_INTA222)
#  define RX66T_INTA223_VNDX         (VECT_PERIA_INTA223)
#  define RX66T_INTA224_VNDX         (VECT_PERIA_INTA224)
#  define RX66T_INTA225_VNDX         (VECT_PERIA_INTA225)
#  define RX66T_INTA226_VNDX         (VECT_PERIA_INTA226)
#  define RX66T_INTA227_VNDX         (VECT_PERIA_INTA227)
#  define RX66T_INTA228_VNDX         (VECT_PERIA_INTA228)
#  define RX66T_INTA229_VNDX         (VECT_PERIA_INTA229)
#  define RX66T_INTA230_VNDX         (VECT_PERIA_INTA230)
#  define RX66T_INTA231_VNDX         (VECT_PERIA_INTA231)
#  define RX66T_INTA232_VNDX         (VECT_PERIA_INTA232)
#  define RX66T_INTA233_VNDX         (VECT_PERIA_INTA233)
#  define RX66T_INTA234_VNDX         (VECT_PERIA_INTA234)
#  define RX66T_INTA235_VNDX         (VECT_PERIA_INTA235)
#  define RX66T_INTA236_VNDX         (VECT_PERIA_INTA236)
#  define RX66T_INTA237_VNDX         (VECT_PERIA_INTA237)
#  define RX66T_INTA238_VNDX         (VECT_PERIA_INTA238)
#  define RX66T_INTA239_VNDX         (VECT_PERIA_INTA239)
#  define RX66T_INTA240_VNDX         (VECT_PERIA_INTA240)
#  define RX66T_INTA241_VNDX         (VECT_PERIA_INTA241)
#  define RX66T_INTA242_VNDX         (VECT_PERIA_INTA242)
#  define RX66T_INTA243_VNDX         (VECT_PERIA_INTA243)
#  define RX66T_INTA244_VNDX         (VECT_PERIA_INTA244)
#  define RX66T_INTA245_VNDX         (VECT_PERIA_INTA245)
#  define RX66T_INTA246_VNDX         (VECT_PERIA_INTA246)
#  define RX66T_INTA247_VNDX         (VECT_PERIA_INTA247)
#  define RX66T_INTA248_VNDX         (VECT_PERIA_INTA248)
#  define RX66T_INTA249_VNDX         (VECT_PERIA_INTA249)
#  define RX66T_INTA250_VNDX         (VECT_PERIA_INTA250)
#  define RX66T_INTA251_VNDX         (VECT_PERIA_INTA251)
#  define RX66T_INTA252_VNDX         (VECT_PERIA_INTA252)
#  define RX66T_INTA253_VNDX         (VECT_PERIA_INTA253)
#  define RX66T_INTA254_VNDX         (VECT_PERIA_INTA254)
#  define RX66T_INTA255_VNDX         (VECT_PERIA_INTA255)

#  define RX66T_NVECTORS             (256)

/* Register information */

#define         REG_SP                          ( 0)
#define         REG_ACC0LO                      ( 1)
#define         REG_ACC0HI                      ( 2)
#define         REG_ACC0GU                      ( 3)
#define         REG_ACC1LO                      ( 4)
#define         REG_ACC1HI                      ( 5)
#define         REG_ACC1GU                      ( 6)
#define         REG_FPSW                        ( 7)
#define         REG_R1                          ( 8)
#define         REG_R2                          ( 9)
#define         REG_R3                          (10)
#define         REG_R4                          (11)
#define         REG_R5                          (12)
#define         REG_R6                          (13)
#define         REG_R7                          (14)
#define         REG_R8                          (15)
#define         REG_R9                          (16)
#define         REG_R10                         (17)
#define         REG_R11                         (18)
#define         REG_R12                         (19)
#define         REG_R13                         (20)
#define         REG_R14                         (21)
#define         REG_R15                         (22)
#define         REG_PC                          (23)
#define         REG_PSW                         (24)
#define         XCPTCONTEXT_REGS        (25)
#define         XCPTCONTEXT_SIZE        (4 * XCPTCONTEXT_REGS)

#ifndef __ASSEMBLY__
struct xcptcontext
{
        /* The following function pointer is non-zero if there are pending signals
         * to be processed.
         */
#ifndef CONFIG_DISABLE_SIGNALS
        void *sigdeliver; /* Actual type is sig_deliver_t */
        /* These are saved copies of LR and SR used during signal processing. */
        uint32_t saved_pc;
        uint32_t saved_sr;
#endif  /* CONFIG_DISABLE_SIGNALS */

        /* Register save area */
        uint32_t regs[XCPTCONTEXT_REGS];
};

/* Name: up_irq_save, up_irq_restore, and friends.
 *
 * NOTE: This function should never be called from application code and,
 * as a general rule unless you really know what you are doing, this
 * function should not be called directly from operation system code either:
 * Typically, the wrapper functions, enter_critical_section() and
 * leave_critical section(), are probably what you really want.
 */

#define RX66T_PSW_INTERRUPT                     (0x00010000)

/* Return the current interrupt enable state and disable IRQs */

/* Get the current value of the SR */

static inline irqstate_t __getsr(void)
{
        irqstate_t flags;
        __asm__ __volatile__("mvfc psw, %0":"=r"(flags));
        return flags;
}

/* Set the new value of the SR */

static inline void __setsr(irqstate_t psw)
{
        __asm__ __volatile__("mvtc %0, psw": :"r"(psw));
}

/* Disable interrupts */
static inline void up_irq_disable(void)
{
        __asm__ __volatile__("CLRPSW I");
}

/* Enable interrupts */
static inline void up_irq_enable(void)
{
        __asm__ __volatile__("SETPSW I");
}

/* Return the current interrupt enable state and disable interrupts */
static inline irqstate_t up_irq_save(void)
{
        irqstate_t flags = __getsr();
        up_irq_disable();
        return flags;
}

/* Restore saved interrupt state */
static inline void up_irq_restore(irqstate_t flags)
{
        if(RX66T_PSW_INTERRUPT == (flags & RX66T_PSW_INTERRUPT))
        {
          up_irq_enable();
        }
        else
        {
          up_irq_disable();
        }
}

#endif  /* __ASSEMBLY__ */

#endif  /* __ARCH_RENESAS_INCLUDE_RX66T_IRQ_H */
